apiVersion: v1
kind: Service
metadata:
  name: orbital
  namespace: orbital
  labels:
    app: orbital
spec:
  type: ClusterIP
  selector:
    app: orbital
  ports:
    - name: http
      port: 80
      targetPort: http
